### ISSUE TITLE
Cannot find module 'gulp-karma'

### ISSUE THREAD

**Issue by 3dd13** [Keats/ng-boilerplate#13]
after bower install and npm install, when I run gulp, the following error comes up:

    Cannot find module 'gulp-karma'

**Comment by 3dd13** [comment]
included the dependency and fix karma and gulp watch error

https://github.com/Keats/ng-boilerplate/pull/14

**Comment by metal3d** [comment]
Theorically, gulp-karma shouldn't be used:
https://github.com/karma-runner/gulp-karma

*You don't need any gulp plugins to run Karma from the Gulp-based build, use Karma directly*

I changed the gulpfile in my pull-request to not use any gulp-karma plugin, that works.

**Comment by Keats** [comment]
Indeed, that code with gulp-karma was something i forgot to delete, should be fixed on master
